name: website

on:
  push:
    branches:
      - master

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: astral-sh/setup-uv@v5

      - name: Install Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: build doc
        run: uv run pdoc -o docs/ src/*

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/


  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4

